export type Country = {
  code: string
  name: string
}

export const OTHER_COUNTRY_CODE = 'OTHER'

export const worldCountries: Country[] = [
  { code: 'AF', name: 'Afeganistao' },
  { code: 'ZA', name: 'Africa do Sul' },
  { code: 'AL', name: 'Albania' },
  { code: 'DE', name: 'Alemanha' },
  { code: 'AD', name: 'Andorra' },
  { code: 'AO', name: 'Angola' },
  { code: 'AG', name: 'Antigua e Barbuda' },
  { code: 'SA', name: 'Arabia Saudita' },
  { code: 'DZ', name: 'Argelia' },
  { code: 'AR', name: 'Argentina' },
  { code: 'AM', name: 'Armenia' },
  { code: 'AU', name: 'Australia' },
  { code: 'AT', name: 'Austria' },
  { code: 'AZ', name: 'Azerbaijao' },
  { code: 'BS', name: 'Bahamas' },
  { code: 'BH', name: 'Bahrein' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'BB', name: 'Barbados' },
  { code: 'BE', name: 'Belgica' },
  { code: 'BZ', name: 'Belize' },
  { code: 'BJ', name: 'Benin' },
  { code: 'BY', name: 'Belarus' },
  { code: 'BO', name: 'Bolivia' },
  { code: 'BA', name: 'Bosnia e Herzegovina' },
  { code: 'BW', name: 'Botsuana' },
  { code: 'BR', name: 'Brasil' },
  { code: 'BN', name: 'Brunei' },
  { code: 'BG', name: 'Bulgaria' },
  { code: 'BF', name: 'Burkina Faso' },
  { code: 'BI', name: 'Burundi' },
  { code: 'BT', name: 'Butao' },
  { code: 'CV', name: 'Cabo Verde' },
  { code: 'CM', name: 'Camaroes' },
  { code: 'KH', name: 'Camboja' },
  { code: 'CA', name: 'Canada' },
  { code: 'QA', name: 'Catar' },
  { code: 'KZ', name: 'Cazaquistao' },
  { code: 'TD', name: 'Chade' },
  { code: 'CL', name: 'Chile' },
  { code: 'CN', name: 'China' },
  { code: 'CY', name: 'Chipre' },
  { code: 'CO', name: 'Colombia' },
  { code: 'KM', name: 'Comores' },
  { code: 'CG', name: 'Congo' },
  { code: 'CD', name: 'Congo (RDC)' },
  { code: 'KP', name: 'Coreia do Norte' },
  { code: 'KR', name: 'Coreia do Sul' },
  { code: 'CI', name: 'Costa do Marfim' },
  { code: 'CR', name: 'Costa Rica' },
  { code: 'HR', name: 'Croacia' },
  { code: 'CU', name: 'Cuba' },
  { code: 'DK', name: 'Dinamarca' },
  { code: 'DJ', name: 'Djibuti' },
  { code: 'DM', name: 'Dominica' },
  { code: 'EG', name: 'Egito' },
  { code: 'SV', name: 'El Salvador' },
  { code: 'AE', name: 'Emirados Arabes Unidos' },
  { code: 'EC', name: 'Equador' },
  { code: 'ER', name: 'Eritreia' },
  { code: 'SK', name: 'Eslovaquia' },
  { code: 'SI', name: 'Eslovenia' },
  { code: 'ES', name: 'Espanha' },
  { code: 'US', name: 'Estados Unidos' },
  { code: 'EE', name: 'Estonia' },
  { code: 'SZ', name: 'Essuatini' },
  { code: 'ET', name: 'Etiopia' },
  { code: 'FJ', name: 'Fiji' },
  { code: 'PH', name: 'Filipinas' },
  { code: 'FI', name: 'Finlandia' },
  { code: 'FR', name: 'Franca' },
  { code: 'GA', name: 'Gabao' },
  { code: 'GM', name: 'Gambia' },
  { code: 'GH', name: 'Gana' },
  { code: 'GE', name: 'Georgia' },
  { code: 'GD', name: 'Granada' },
  { code: 'GR', name: 'Grecia' },
  { code: 'GT', name: 'Guatemala' },
  { code: 'GY', name: 'Guiana' },
  { code: 'GF', name: 'Guiana Francesa' },
  { code: 'GN', name: 'Guine' },
  { code: 'GW', name: 'Guine-Bissau' },
  { code: 'GQ', name: 'Guine Equatorial' },
  { code: 'HT', name: 'Haiti' },
  { code: 'NL', name: 'Holanda' },
  { code: 'HN', name: 'Honduras' },
  { code: 'HK', name: 'Hong Kong' },
  { code: 'HU', name: 'Hungria' },
  { code: 'YE', name: 'Iemen' },
  { code: 'IN', name: 'India' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'IQ', name: 'Iraque' },
  { code: 'IR', name: 'Ira' },
  { code: 'IE', name: 'Irlanda' },
  { code: 'IS', name: 'Islandia' },
  { code: 'IL', name: 'Israel' },
  { code: 'IT', name: 'Italia' },
  { code: 'JM', name: 'Jamaica' },
  { code: 'JP', name: 'Japao' },
  { code: 'JO', name: 'Jordania' },
  { code: 'XK', name: 'Kosovo' },
  { code: 'KW', name: 'Kuwait' },
  { code: 'LA', name: 'Laos' },
  { code: 'LS', name: 'Lesoto' },
  { code: 'LV', name: 'Letonia' },
  { code: 'LB', name: 'Libano' },
  { code: 'LR', name: 'Liberia' },
  { code: 'LY', name: 'Libia' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'LT', name: 'Lituania' },
  { code: 'LU', name: 'Luxemburgo' },
  { code: 'MO', name: 'Macau' },
  { code: 'MK', name: 'Macedonia do Norte' },
  { code: 'MG', name: 'Madagascar' },
  { code: 'MY', name: 'Malasia' },
  { code: 'MW', name: 'Malaui' },
  { code: 'MV', name: 'Maldivas' },
  { code: 'ML', name: 'Mali' },
  { code: 'MT', name: 'Malta' },
  { code: 'MA', name: 'Marrocos' },
  { code: 'MU', name: 'Mauricio' },
  { code: 'MR', name: 'Mauritania' },
  { code: 'MX', name: 'Mexico' },
  { code: 'MM', name: 'Mianmar' },
  { code: 'MZ', name: 'Mocambique' },
  { code: 'MD', name: 'Moldavia' },
  { code: 'MC', name: 'Monaco' },
  { code: 'MN', name: 'Mongolia' },
  { code: 'ME', name: 'Montenegro' },
  { code: 'NA', name: 'Namibia' },
  { code: 'NP', name: 'Nepal' },
  { code: 'NI', name: 'Nicaragua' },
  { code: 'NE', name: 'Niger' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'NO', name: 'Noruega' },
  { code: 'NZ', name: 'Nova Zelandia' },
  { code: 'OM', name: 'Oma' },
  { code: 'PW', name: 'Palau' },
  { code: 'PS', name: 'Palestina' },
  { code: 'PA', name: 'Panama' },
  { code: 'PG', name: 'Papua-Nova Guine' },
  { code: 'PK', name: 'Paquistao' },
  { code: 'PY', name: 'Paraguai' },
  { code: 'PE', name: 'Peru' },
  { code: 'PF', name: 'Polinesia Francesa' },
  { code: 'PL', name: 'Polonia' },
  { code: 'PR', name: 'Porto Rico' },
  { code: 'PT', name: 'Portugal' },
  { code: 'KE', name: 'Quenia' },
  { code: 'KG', name: 'Quirguistao' },
  { code: 'GB', name: 'Reino Unido' },
  { code: 'CF', name: 'Republica Centro-Africana' },
  { code: 'DO', name: 'Republica Dominicana' },
  { code: 'RO', name: 'Romenia' },
  { code: 'RW', name: 'Ruanda' },
  { code: 'RU', name: 'Russia' },
  { code: 'SB', name: 'Ilhas Salomao' },
  { code: 'WS', name: 'Samoa' },
  { code: 'SM', name: 'San Marino' },
  { code: 'LC', name: 'Santa Lucia' },
  { code: 'ST', name: 'Sao Tome e Principe' },
  { code: 'SN', name: 'Senegal' },
  { code: 'SL', name: 'Serra Leoa' },
  { code: 'RS', name: 'Servia' },
  { code: 'SC', name: 'Seicheles' },
  { code: 'SG', name: 'Singapura' },
  { code: 'SY', name: 'Siria' },
  { code: 'SO', name: 'Somalia' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'SD', name: 'Sudao' },
  { code: 'SS', name: 'Sudao do Sul' },
  { code: 'SE', name: 'Suecia' },
  { code: 'CH', name: 'Suica' },
  { code: 'SR', name: 'Suriname' },
  { code: 'TH', name: 'Tailandia' },
  { code: 'TW', name: 'Taiwan' },
  { code: 'TJ', name: 'Tadjiquistao' },
  { code: 'TZ', name: 'Tanzania' },
  { code: 'TL', name: 'Timor-Leste' },
  { code: 'TG', name: 'Togo' },
  { code: 'TO', name: 'Tonga' },
  { code: 'TT', name: 'Trinidad e Tobago' },
  { code: 'TN', name: 'Tunisia' },
  { code: 'TM', name: 'Turcomenistao' },
  { code: 'TR', name: 'Turquia' },
  { code: 'UA', name: 'Ucrania' },
  { code: 'UG', name: 'Uganda' },
  { code: 'UY', name: 'Uruguai' },
  { code: 'UZ', name: 'Uzbequistao' },
  { code: 'VU', name: 'Vanuatu' },
  { code: 'VA', name: 'Vaticano' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'VN', name: 'Vietna' },
  { code: 'ZM', name: 'Zambia' },
  { code: 'ZW', name: 'Zimbabue' },
]

export function getWorldCountryName(code: string) {
  if (code === OTHER_COUNTRY_CODE) {
    return 'Outro'
  }

  return worldCountries.find((country) => country.code === code)?.name ?? code
}
